# Site settings
title: Mohamat Eirban Ali portfolio 
description: Mohamat Eirban Ali portfolio 
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Mohamat Eirban Ali
user_description: Hi, my name is Mohamat. I am orginally from Malaysia and currently residing in the United States for 5 years. I graduated Cum Laude in Bachelors of Science in Mechanical Engineering from University of Central Oklahoma (UCO) and currently in my last semester of Masters degree at the University of Oklahoma (OU) in Electrical and Computer Engineering department. I have 4 years of experience in research roles and heavily involved in data science, PCB design and testing, Linux embedded and IOT systems.
user_title: Electrical and Computer Engineer with Mechanical Engineering background. Data Scientist.
email: irfan93@ou.edu
github_username:  Irfan93


# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
